### ISSUE TITLE
Future features

### ISSUE THREAD

**Issue by alecgorge** [palaniraja/mclock#4]
I just purchased the app store version and I am looking forward to the pro updates.

Do you have a timeline for when second by second updates and multiple timezone support will be available?

**Comment by palaniraja** [comment]
Hi Alec,

Thank you for purchasing.

By mistake I've uploaded the old version to appstore. I'm planning to update the recent version by this weekend. So hopefully it will be published in a week or two.

To your request, Implementation of second by second update is straight forward, but I took a stand not to consume too much power/battery just for a every second update. Hence, 60 sec update cycle. Was thinking about reducing it to like 45/30 sec update to solve a known issue. (if your system is sleep and mclock update only after 60 sec since awake.)

May I know the usecase for every second update? 

Thank you once again for the purchase.

**Comment by alecgorge** [comment]
I use a desktop that literally is never asleep and thus power and battery is not a concern. I also have my system clock set to show seconds and I would like them to match

**Comment by palaniraja** [comment]
Fixed in v2.2 (submitted to appstore today). Should be available in 2-3 weeks.

If you include the second modifier 's' your time is updated every second. Else it will get updated every minute the old way.

Multiple timezone is next in the list. I'm still thinking of a simpler UI without removing minimalist 'm' from mclock.
